repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    - id: flake8
      args: ['--max-line-length=88', 
            '--ignore=F403, F405, E711, W503'
            ]